istio:
  enabled: true
  global:
    mtls:
      enabled: true
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
    egressGateways: []
    pilot:
      enabled: true
  meshConfig:
    defaultConfig:
      mtls:
        mode: STRICT
  policy:
    enabled: true
    enforce: true