apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opa.fullname" . }}
  labels:
    {{- include "opa.labels" . | nindent 4 }}
    component: opa
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "opa.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: opa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "opa.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: opa
    spec:
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: opa
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          args:
            - "run"
            - "--server"
            - "--addr=0.0.0.0:8181"
          ports:
            - containerPort: 8181
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
