apiVersion: v1
kind: Service
metadata:
  name: somaagent
  namespace: agent
  labels:
    app: somaagent
spec:
  selector:
    app: somaagent
  ports:
    - protocol: TCP
      port: 63900
      targetPort: 9000
      name: http-api
  type: ClusterIP
