apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

images:
  - name: somatechlat/agent-zero
    newTag: latest

secretGenerator:
  - name: telemetry-postgres
    literals:
      - dsn=postgresql://soma:soma@postgres.somaagent.svc.cluster.local:5432/somaagent01
  - name: delegation-postgres
    literals:
      - dsn=postgresql://soma:soma@postgres.somaagent.svc.cluster.local:5432/somaagent01

generatorOptions:
  disableNameSuffixHash: true
